before_install: gem install bundler -v 2.0.1
cache: bundler
gemfile:
  - gemfiles/railties_4.2.gemfile
  - gemfiles/railties_5.0.gemfile
  - gemfiles/railties_5.1.gemfile
  - gemfiles/railties_5.2.gemfile
  - gemfiles/railties_5.x.gemfile
language: ruby
matrix:
  fast_finish: true
rvm:
  - 2.4.5
  - 2.5.5
  - 2.6.2
notifications:
  email:
    on_failure: always
    on_success: change
sudo: false
