trigger:
- master

jobs:
  - job: "sha_header"
    pool:
      vmImage: 'Ubuntu-16.04'
    strategy:
      matrix:
        Ruby 2.4.x railties 4.2:
          rubyVersion: '2.4.x'
          gemfile: 'railties_4.2'
        Ruby 2.4.x railties 5.0:
          rubyVersion: '2.4.x'
          gemfile: 'railties_5.0'
        Ruby 2.4.x railties 5.1:
          rubyVersion: '2.4.x'
          gemfile: 'railties_5.1'
        Ruby 2.4.x railties 5.2:
          rubyVersion: '2.4.x'
          gemfile: 'railties_5.2'
        Ruby 2.4.x railties 5.x:
          rubyVersion: '2.4.x'
          gemfile: 'railties_5.x'
        Ruby 2.5.x railties 4.2:
          rubyVersion: '2.5.x'
          gemfile: 'railties_4.2'
        Ruby 2.5.x railties 5.0:
          rubyVersion: '2.5.x'
          gemfile: 'railties_5.0'
        Ruby 2.5.x railties 5.1:
          rubyVersion: '2.5.x'
          gemfile: 'railties_5.1'
        Ruby 2.5.x railties 5.2:
          rubyVersion: '2.5.x'
          gemfile: 'railties_5.2'
        Ruby 2.5.x railties 5.x:
          rubyVersion: '2.5.x'
          gemfile: 'railties_5.x'
    steps:
    - task: UseRubyVersion@0
      inputs:
        versionSpec: '$(rubyVersion)'
    - script: |
        export BUNDLE_GEMFILE=$PWD/gemfiles/$(gemfile).gemfile
        gem install bundler -v 2.0.1
        bundle install --retry=3 --jobs=4
      displayName: 'bundle install'
    - script: |
        export BUNDLE_GEMFILE=$PWD/gemfiles/$(gemfile).gemfile
        bundle exec rake
      displayName: 'bundle exec rake'
